services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn project_name.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project_name.settings
      - key: SECRET_KEY
        value: 
      - key: DEBUG
        value: 'False'
    staticPublish:
      - path: /static
        name: staticfiles
      - path: /media
        name: mediafiles
