# Generated by Django 5.1.2 on 2024-11-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_history',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_history_buyer', to='users.student'),
        ),
        migrations.AddField(
            model_name='shop_history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_history_product', to='shop.products'),
        ),
    ]
