# Generated by Django 5.1.2 on 2024-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_history',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
